#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
#By considering the terms in the Fibonacci sequence whose values do not exceed four million
#find the sum of the even-valued terms.

def fibonacci():
    f = [1,2]
    total = 0
    for i in range(1,50):
        f.append(f[i]+f[i-1])  

        if(f[i] % 2==0 and f[i] < 4000000):
            total += f[i]
    print(total)
    
fibonacci()
#output is 4613732
